#!/usr/bin/bash

version=1.0.0
SERVER_URL=http://172.17.0.1

CMD=$1
DOCKER_NAME=xtop
DOCKER_IMAGE_NAME=cool/xtop


case $CMD in
    debug)
        source .venv/bin/activate
        python3 main.py
    ;;
    build)
        docker build -f Dockerfile --tag ${DOCKER_IMAGE_NAME}:$version .
        docker tag ${DOCKER_IMAGE_NAME}:$version ${DOCKER_IMAGE_NAME}:latest
    ;;

    up)
        docker run -it --restart unless-stopped \
                --name ${DOCKER_NAME} \
                --privileged \
                -e SERVER_URL=${SERVER_URL} \
                -v /dev/bus/usb:/dev/bus/usb \
                -v /dev/dri:/dev/dri \
                -v /etc/localtime:/etc/localtime \
                -v /var/run/docker.sock:/var/run/docker.sock \
                ${DOCKER_IMAGE_NAME}:latest
        docker stop ${DOCKER_NAME}
        docker rm ${DOCKER_NAME}
    ;;

    down)
        docker stop ${DOCKER_NAME}
        docker rm ${DOCKER_NAME}
    ;;

    logs)
        docker logs -f ${DOCKER_NAME}
    ;;

    exec)
        docker exec -it ${DOCKER_NAME} bash
    ;;

    push)
        docker push ${DOCKER_IMAGE_NAME}:$version
        docker push ${DOCKER_IMAGE_NAME}:latest
    ;;

    *)
        echo "xtop: Monitor for FPS, System Usage and Docker Stats"
        echo "Usage:"
        echo "bash xtop build"
        echo "    build the docker image."
        echo "bash xtop up"
        echo "    start the docker container"
        echo "bash xtop down"
        echo "    stop the docker container"
        echo "bash xtop logs"
        echo "    print the logs of the docker container"
        echo "bash xtop push"
        echo "    push the current image to docker hub"
esac
